version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: english_learning_db
    environment:
      POSTGRES_DB: english_learning
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - english_learning_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: english_learning_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: english_learning
      DB_SSLMODE: disable
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_ACCESS_EXPIRY: 60
      JWT_REFRESH_EXPIRY: 24
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - english_learning_network
    volumes:
      - ./backend:/app
      - /app/tmp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: english_learning_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - backend
    networks:
      - english_learning_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  english_learning_network:
    driver: bridge

